version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: npm install
      - run: npm run build
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build
