version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run:
          name: Installing ts-node
          command: npm install --no-save ts-node

workflows:
  build_and_test:
    jobs:
      - build
