version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm run prettier:check
      - run: npm run build
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build
